name: dtumaps
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For Bottom Sheet
  sliding_up_panel: ^2.0.0+1
  
  # For Button
  group_button: ^3.3.1

  # For Carousel
  carousel_slider: ^4.0.0

  # For Icons
  eva_icons_flutter: ^3.0.2

  # For model
  json_serializable: ^4.1.3
  freezed_annotation: ^0.14.2
  animated_theme_switcher: ^2.0.1-nullsafety.0

  # For Architecture
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4

  # For Networking
  dio: ^4.0.0
  retrofit: ^2.0.0
  cached_network_image: ^3.1.0

  # For Map
  flutter_map: any
  latlong2: any

  # For User Location
  geolocator: 7.6.2

  # For local data
  shared_preferences: any

  # For Searching
  rxdart: ^0.27.2

  # For Icons and Assets
  material_floating_search_bar: ^0.3.4
  line_icons: ^2.0.1
  flutter_svg: ^0.22.0
  modal_bottom_sheet: ^2.0.0
  swipedetector: ^1.2.0
  photo_view: ^0.4.0
  swipe_image_gallery: ^0.0.4
  lottie: ^1.2.1
  image_picker: ^0.8.4+3
  image_cropper: ^1.2.1
  image_picker_web: ^2.0.3+1

  # format date time
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.4
  simple_animations: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  nb_utils: ^4.4.8
  # For Networking
  retrofit_generator: ^2.0.0+1

  # For Model
  freezed: ^0.14.2
  flutter_launcher_icons: "^0.9.2"
flutter:
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/map/
    - assets/SVG/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sdm_icon.png"
